name: PROD Deployment

on:
  push:
    branches:
      - "production"

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      DEPLOYMENT_ENVIRONMENT: jobs.deployment.environment
    steps:
      - run: echo Deploying to $DEPLOYMENT_ENVIRONMENT